/** Normaliza chaves retornadas pelo Postgres (aliases sem aspas viram minúsculas). */
const KEY_ALIASES = {
  pipelineid: 'pipelineId',
  stagekey: 'stageKey',
  empresaid: 'empresaId',
  isdefault: 'isDefault',
  contatoid: 'contatoId',
  contatoemail: 'contatoEmail',
  contatotelefone: 'contatoTelefone',
  contatonome: 'contatoNome',
  dealid: 'dealId',
  proximaacao: 'proximaAcao',
  ultimainteracao: 'ultimaInteracao',
  precisafollowup: 'precisaFollowUp',
  enviadaem: 'enviadaEm',
  baseurl: 'baseUrl',
  instancename: 'instanceName',
  apikey: 'apiKey',
  webhooksecret: 'webhookSecret',
  maxpos: 'maxPos',
  phonenumberid: 'phoneNumberId',
  accesstoken: 'accessToken',
  verifytoken: 'verifyToken',
  graphversion: 'graphVersion',
  appsecret: 'appSecret',
  wabaid: 'wabaId',
  metaappid: 'metaAppId',
  remotejid: 'remoteJid',
  contactid: 'contactId',
  contactname: 'contactName',
  lastmessage: 'lastMessage',
  lastmessageat: 'lastMessageAt',
  fromme: 'fromMe',
  messageat: 'messageAt',
  wamessageid: 'waMessageId',
  attendancestatus: 'attendanceStatus',
  userid: 'userId',
  useform: 'useForm',
  startat: 'startAt',
  remindminutes: 'remindMinutes',
  attendeeresponses: 'attendeeResponses',
  googleeventid: 'googleEventId',
  googlehtmllink: 'googleHtmlLink',
  googleownerid: 'googleOwnerId',
  googleetag: 'googleEtag',
  calendarid: 'calendarId',
  importevents: 'importEvents',
  synctoken: 'syncToken',
  lastsyncedat: 'lastSyncedAt',
  refid: 'refId',
  readat: 'readAt',
  endat: 'endAt',
  allday: 'allDay',
  completedat: 'completedAt',
  createdby: 'createdBy',
  authorname: 'authorName',
  authorid: 'authorId',
  owneruserid: 'ownerUserId',
  ownerroundrobin: 'ownerRoundRobin',
  ownerid: 'ownerId',
  siteurl: 'siteUrl',
  sitename: 'siteName',
  monitorcode: 'monitorCode',
  pipelinename: 'pipelineName',
  stagetitle: 'stageTitle',
  pageviews: 'pageViews',
  buttonclicks: 'buttonClicks',
  lastseenat: 'lastSeenAt',
  createdat: 'createdAt',
  updatedat: 'updatedAt',
  fileurl: 'fileUrl',
  filename: 'fileName',
  mimetype: 'mimeType',
  filesize: 'fileSize',
  templateid: 'templateId',
  fieldvalues: 'fieldValues',
  emailsentat: 'emailSentAt',
  errormessage: 'errorMessage',
  expiresat: 'expiresAt',
  acceptedat: 'acceptedAt',
  accountname: 'accountName',
  accountid: 'accountId',
  invitedby: 'invitedBy',
  assignedto: 'assignedTo',
  assignedtoname: 'assignedToName',
  welcomemessageenabled: 'welcomeMessageEnabled',
  welcomemessagetext: 'welcomeMessageText',
};

export function normalizeRow(row) {
  if (!row || typeof row !== 'object') return row;
  const out = { ...row };
  for (const [lower, camel] of Object.entries(KEY_ALIASES)) {
    if (out[camel] === undefined && out[lower] !== undefined) {
      out[camel] = out[lower];
    }
  }
  return out;
}

export function normalizeRows(rows) {
  return Array.isArray(rows) ? rows.map(normalizeRow) : [];
}
